<?php
/**
 * @file
 * Drupal Module: Hotjar.
 *
 * Adds the required Javascript to all your Drupal pages to allow
 * tracking by hotjar (https://www.hotjar.com/).
 */

use Drupal\Component\Utility\Unicode;

/**
 * Define default path exclusion list to remove tracking from admin pages.
 *
 * See http://drupal.org/node/34970 for more information.
 */
define('HOTJAR_PAGES', "/admin\n/admin/*\n/batch\n/node/add*\n/node/*/*\n/user/*/*");

/**
 * Implements hook_help().
 */
function hotjar_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'hotjar.admin_settings_form':
      return t('<a href="@hotjar_url">Hotjar</a> is a new powerful way to reveal true website user behaviour and experiences in one central tool – giving you the big picture of how you can improve your site\'s UX and conversion rates. All your data is securely stored in the cloud and is accessible at lightning speed.', array('@hotjar_url' => 'https://www.hotjar.com/'));
  }
}

/**
 * Get Hotjar settings.
 */
function hotjar_get_settings() {
  $settings = (array) \Drupal::config('hotjar.settings')->getOriginal();
  $settings += array(
    'account' => NULL,
    'visibility_pages' => 0,
    'pages' => HOTJAR_PAGES,
    'visibility_roles' => 0,
    'roles' => array(),
  );
  return $settings;
}

/**
 * Implements hook_page_attachments().
 *
 * Insert JavaScript to the <head> tag of the page.
 */
function hotjar_page_attachments(array &$attachments) {
  $settings = hotjar_get_settings();
  $id = $settings['account'];

  if (
    !$id
    || !_hotjar_check_status()
    || !_hotjar_should_be_added()
    || !_hotjar_check_user()
  ) {
    return;
  }

  // Use escaped HotjarID.
  $clean_id = json_encode($id, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);

  // Quote from the Hotjar dashboard:
  // "The Tracking Code below should be placed in the <head> tag of
  // every page you want to track on your site."
  $tracking_code = <<<HJ
(function(h,o,t,j,a,r){
  h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
  h._hjSettings={hjid:{$clean_id},hjsv:5};
  a=o.getElementsByTagName('head')[0];
  r=o.createElement('script');r.async=1;
  r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
  a.appendChild(r);
})(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
HJ;

  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#value' => $tracking_code,
    ],
    'hotjar_tracking_code'
  ];
}

/**
 * Check Hotjar code should be added.
 */
function _hotjar_should_be_added() {
  $page_match = &drupal_static(__FUNCTION__);
  if (isset($page_match)) {
    return $page_match;
  }

  $settings = hotjar_get_settings();

  $visibility = $settings['visibility_pages'];
  $setting_pages = $settings['pages'];

  if (empty($setting_pages)) {
    $page_match = TRUE;
    return $page_match;
  }

  $pages = Unicode::strtolower($setting_pages);
  if ($visibility < 2) {
    $path = \Drupal::service('path.current')->getPath();
    $path_alias = Unicode::strtolower(\Drupal::service('path.alias_manager')->getAliasByPath($path));
    $path_match = \Drupal::service('path.matcher')->matchPath($path_alias, $pages);
    $alias_match = (($path != $path_alias) && \Drupal::service('path.matcher')->matchPath($path, $pages));
    $page_match = $path_match || $alias_match;

    // When $visibility has a value of 0, the tracking code is displayed on
    // all pages except those listed in $pages. When set to 1, it
    // is displayed only on those pages listed in $pages.
    $page_match = !($visibility xor $page_match);
  }
  else {
    $page_match = FALSE;
  }

  return $page_match;
}

/**
 * Check Hotjar code should be added for user.
 */
function _hotjar_check_user($account = NULL) {
  if (!isset($account)) {
    $account = \Drupal::currentUser();
  }

  $enabled = FALSE;
  if (_hotjar_check_roles($account)) {
    $enabled = TRUE;
  }

  return $enabled;

}

/**
 * Check user role.
 */
function _hotjar_check_roles($account = NULL) {
  /** @var Drupal\Core\Session\AccountProxy $account */
  if (!isset($account)) {
    $account = \Drupal::currentUser();
  }

  $settings = hotjar_get_settings();
  $visibility = $settings['visibility_roles'];
  $enabled = $visibility;
  $roles = $settings['roles'];

  // The hotjar_roles stores the selected roles as an array where
  // the keys are the role IDs. When the role is not selected the
  // value is 0. If a role is selected the value is the role ID.
  $checked_roles = array_filter($roles);
  if (empty($checked_roles)) {
    // No role is selected for tracking, therefore all roles should be tracked.
    return TRUE;
  }

  if (count(array_intersect($account->getRoles(), $checked_roles))) {
    $enabled = !$visibility;
  }

  return $enabled;
}

/**
 * Check current request HTTP status.
 */
function _hotjar_check_status() {
  // Get page status code for visibility filtering.
  $request = \Drupal::request();
  $status = NULL;
  if ($exception = $request->attributes->get('exception')) {
    $status = $exception->getStatusCode();
  }
  $not_tracked_status_codes = array(
    '403',
    '404',
  );
  return !in_array($status, $not_tracked_status_codes);
}
