# Schema for the configuration files of the hotjar module.

hotjar.settings:
  type: config_object
  label: 'Hotjar settings'
  mapping:
    account:
      type: string
      label: 'Hotjar ID'
    visibility_pages:
      type: integer
      label: 'Add tracking to specific pages'
    pages:
      type: string
      label: 'Pages by their paths'
    visibility_roles:
      type: integer
      label: 'Add tracking for specific roles'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
